Adds new ``BCRYPTHashingScheme``.
zopefoundation/AuthEncoding pull request #1
Opened 2016-09-30 20:37 UTC by mgrbyte

- Only available if package is installed with the `bcrypt` extra.

@icemac  Following up from [previous discussions](https://github.com/zopefoundation/AccessControl/pull/11#issuecomment-250685627),
this PR adds optional bcrypt support to `AuthEncoding`.

Please note the following omissions:
 - I've not set a version pin for the `bcrypt` package (I used latest, which at time of writing was `3.1.1`)
 - Tests slow down a lot (tests take ~16 seconds on my laptop)

2016-10-01 07:37 UTC, mgedmin requested changes

2016-10-01 07:37 UTC, mgedmin commented on src/AuthEncoding/AuthEncoding.py
> +                 valid = hashed == reference
I think you should use `bcrypt.checkpw()`.  I am not a cryptographer, but I remember something about constant-time comparisons of hashes being important.

2016-10-02 01:43 UTC, mgrbyte commented on src/AuthEncoding/AuthEncoding.py
> +                 valid = hashed == reference
Yes, this was a very dumb attempt/implementation from the original code, I seem to recall "fixing" this in previous code somewhere in the distance past... *sighs*   - fixed in  db76353071f28fa1ff02b7a02b602bd6fe418a18
FWIW, there's a great deal of overlap/duplication of this AuthEncoding API vs zope.password,
where I'd previously put work in to [attempt](https://github.com/zopefoundation/zope.password/pull/1) to implement `bcrypt` support.

2016-10-02 15:32 UTC, tseaver requested changes
Thanks for the patch!

2016-10-02 15:32 UTC, tseaver commented on src/AuthEncoding/AuthEncoding.py
> +if bcrypt is not None:
As in https://github.com/zopefoundation/zope.password/pull/5#pullrequestreview-2450238, please update to define the class unconditionally, but raise in `__init__()` if `bcrypt` is None.  That would require a conditional test of that constructor, too.

I don't see any added tests in this PR:  do the parameterized tests actually cover everything for the new handler?

2016-10-02 15:32 UTC, tseaver commented on src/AuthEncoding/AuthEncoding.py
> +    registerScheme(u'BCRYPT', BCRYPTHashingScheme())
*This* statement should be guarded by the `if bcrypt is not None:` check, however.

2016-10-02 15:32 UTC, tseaver commented on src/AuthEncoding/AuthEncoding.py
> +                 valid = bcrypt.checkpw(_ensure_bytes(attempt), reference)
Seems like a good case for early return:

```python
             try:
                 return bcrypt.checkpw(_ensure_bytes(attempt), reference)
             except ValueError:
                 # Usually due to an invalid salt
                 return False
```

2016-10-02 21:28 UTC, mgrbyte commented on src/AuthEncoding/AuthEncoding.py
> +if bcrypt is not None:
I believe the parameterized tests do cover everything for the new handler (at least as much as they do for all the other handlers)

2016-10-02 21:42 UTC, mgrbyte commented
Related to both this PR and the one in zope.password, see also [this](/pyca/bcrypt/pull/95) with regard to `bcrypt.checkpw`.  I don't think it's a show stopper, but something to be aware of.

2016-10-03 01:53 UTC, merged

2016-10-03 01:54 UTC, tseaver commented
@mgrbyte Thanks again!

@mgedmin I verified that the change you asked for was there before merging.